import json
import logging
import math
import os
import random
import sys
import threading
import time
import uuid
from typing import Any

import redis
import uvicorn
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import Response
from pydantic import BaseModel, Field
from prometheus_client import (
    CONTENT_TYPE_LATEST,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
    start_http_server,
)
from psycopg_pool import ConnectionPool

from scenario import PHASES, ScenarioClock


logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s %(levelname)s %(message)s",
)
LOGGER = logging.getLogger("metric-lab")

SERVICE_NAME = os.getenv("SERVICE_NAME", "metric-lab-app")
POSTGRES_DSN = os.getenv("POSTGRES_DSN", "postgresql://lab:lab@postgres:5432/metriclab")
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
APP_PORT = int(os.getenv("APP_PORT", "8000"))
METRICS_PORT = int(os.getenv("METRICS_PORT", "9108"))
SESSION_TTL_SECONDS = int(os.getenv("SESSION_TTL_SECONDS", "900"))

CLOCK = ScenarioClock()
RANDOM = random.Random()

DB_POOL: ConnectionPool | None = None
REDIS_CLIENT: redis.Redis | None = None
SESSIONS: dict[str, float] = {}
SESSIONS_LOCK = threading.Lock()

HTTP_REQUESTS = Counter(
    "lab_http_requests_total",
    "HTTP requests served by the synthetic metric lab app",
    ["service", "endpoint", "method", "status_class", "outcome"],
)
HTTP_DURATION = Histogram(
    "lab_http_request_duration_seconds",
    "HTTP request latency of the synthetic metric lab app",
    ["service", "endpoint", "method"],
    buckets=(0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.35, 0.5, 0.75, 1.0, 2.0, 3.0, 5.0),
)
DB_DURATION = Histogram(
    "lab_db_operation_duration_seconds",
    "PostgreSQL operation latency of the synthetic metric lab stack",
    ["service", "operation", "outcome"],
    buckets=(0.001, 0.003, 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.2, 0.5, 1.0),
)
WORKER_JOBS = Counter(
    "lab_worker_jobs_total",
    "Background worker jobs handled by the metric lab worker",
    ["service", "job_type", "outcome"],
)
WORKER_DURATION = Histogram(
    "lab_worker_job_duration_seconds",
    "Background worker job latency",
    ["service", "job_type", "outcome"],
    buckets=(0.025, 0.05, 0.1, 0.2, 0.35, 0.5, 0.75, 1.0, 2.0, 3.0, 5.0),
)
BUSINESS_EVENTS = Counter(
    "lab_business_events_total",
    "Business events generated by the synthetic stack",
    ["service", "event", "outcome"],
)
ACTIVE_SESSIONS = Gauge(
    "lab_active_sessions",
    "Approximate number of active user sessions",
    ["service"],
)
TOTAL_CART_ITEMS = Gauge(
    "lab_cart_items_total",
    "Total number of items currently present in carts",
    ["service"],
)
QUEUE_DEPTH = Gauge(
    "lab_queue_depth",
    "Length of the Redis checkout queue",
    ["service"],
)
ORDERS_PENDING = Gauge(
    "lab_orders_pending_total",
    "Orders that are still pending shipment",
    ["service"],
)
WORKER_BACKPRESSURE = Gauge(
    "lab_worker_backpressure_ratio",
    "Queue depth divided by the current scenario target users",
    ["service"],
)
SCENARIO_PHASE = Gauge(
    "lab_scenario_phase",
    "Current scenario phase represented as a one-hot gauge",
    ["service", "phase"],
)
LATENCY_INJECTION = Gauge(
    "lab_latency_injection_seconds",
    "Latency injected by the current scenario phase",
    ["service", "phase"],
)
ERROR_INJECTION = Gauge(
    "lab_error_injection_ratio",
    "Error ratio injected by the current scenario phase",
    ["service", "phase"],
)
CACHE_REQUESTS = Counter(
    "lab_cache_requests_total",
    "Cache requests performed by the synthetic application",
    ["service", "cache", "outcome"],
)
CHECKOUT_VALUE = Histogram(
    "lab_checkout_value_rubles",
    "Checkout basket values in rubles",
    ["service"],
    buckets=(500, 1000, 1500, 2000, 3000, 5000, 8000, 12000),
)


class CartAddRequest(BaseModel):
    product_id: str = Field(min_length=3)
    quantity: int = Field(default=1, ge=1, le=6)


app = FastAPI(title="Metric Lab Synthetic API", version="1.0.0")


def get_db_pool() -> ConnectionPool:
    global DB_POOL
    if DB_POOL is None:
        DB_POOL = ConnectionPool(
            conninfo=POSTGRES_DSN,
            min_size=1,
            max_size=8,
            timeout=10,
            open=False,
            kwargs={"autocommit": True},
        )
    return DB_POOL


def get_redis_client() -> redis.Redis:
    global REDIS_CLIENT
    if REDIS_CLIENT is None:
        REDIS_CLIENT = redis.Redis.from_url(REDIS_URL, decode_responses=True)
    return REDIS_CLIENT


def wait_for_dependencies(timeout_seconds: int = 90) -> None:
    deadline = time.time() + timeout_seconds
    last_error: Exception | None = None
    while time.time() < deadline:
        try:
            pool = get_db_pool()
            pool.open(wait=True)
            with pool.connection() as connection:
                connection.execute("select 1")
            get_redis_client().ping()
            return
        except Exception as error:            last_error = error
            time.sleep(2)
    raise RuntimeError(f"Dependencies are not ready: {last_error}") from last_error


def current_phase():
    return CLOCK.current_phase()


def random_sleep(bounds: tuple[float, float]) -> None:
    low, high = bounds
    time.sleep(RANDOM.uniform(low, high))


def burn_cpu(milliseconds: int) -> None:
    if milliseconds <= 0:
        return
    deadline = time.perf_counter() + (milliseconds / 1000.0)
    accumulator = 0.0
    while time.perf_counter() < deadline:
        accumulator += math.sqrt(9876.54321)
    if accumulator < 0:
        LOGGER.debug("Unreachable branch to keep the accumulator alive: %s", accumulator)


def observe_request(endpoint: str, method: str, status_code: int, outcome: str, started_at: float) -> None:
    HTTP_REQUESTS.labels(
        service=SERVICE_NAME,
        endpoint=endpoint,
        method=method,
        status_class=f"{status_code // 100}xx",
        outcome=outcome,
    ).inc()
    HTTP_DURATION.labels(service=SERVICE_NAME, endpoint=endpoint, method=method).observe(
        time.perf_counter() - started_at
    )


def execute_endpoint(endpoint: str, method: str, handler, failure_detail: str):
    started_at = time.perf_counter()
    status_code = 200
    outcome = "success"
    try:
        return handler()
    except HTTPException as error:
        status_code = error.status_code
        outcome = "error"
        raise
    except Exception as error:        LOGGER.exception("Unhandled error for %s", endpoint)
        status_code = 500
        outcome = "error"
        raise HTTPException(status_code=500, detail=failure_detail) from error
    finally:
        observe_request(endpoint, method, status_code, outcome, started_at)


def run_db(operation: str, query: str, params: tuple[Any, ...] = (), fetch: str = "none"):
    started_at = time.perf_counter()
    outcome = "success"
    try:
        with get_db_pool().connection() as connection:
            cursor = connection.execute(query, params)
            if fetch == "all":
                return cursor.fetchall()
            if fetch == "one":
                return cursor.fetchone()
            return None
    except Exception:
        outcome = "error"
        raise
    finally:
        DB_DURATION.labels(service=SERVICE_NAME, operation=operation, outcome=outcome).observe(
            time.perf_counter() - started_at
        )


def product_to_dict(row) -> dict[str, Any]:
    return {
        "id": row[0],
        "name": row[1],
        "category": row[2],
        "price_rub": round(row[3] / 100.0, 2),
        "popularity": row[4],
    }


def touch_session(session_id: str) -> None:
    with SESSIONS_LOCK:
        SESSIONS[session_id] = time.time()


def current_session_id(request: Request) -> str:
    raw_value = request.headers.get("x-session-id", "").strip()
    session_id = raw_value or f"session-{uuid.uuid4().hex[:12]}"
    touch_session(session_id)
    return session_id


def cart_key(session_id: str) -> str:
    return f"cart:{session_id}"


def fetch_featured_products(limit: int = 8) -> list[dict[str, Any]]:
    rows = run_db(
        "featured_products",
        "select id, name, category, price_cents, popularity from products order by popularity desc limit %s",
        (limit,),
        fetch="all",
    )
    return [product_to_dict(row) for row in rows]


def fetch_products_by_ids(product_ids: list[str]) -> dict[str, dict[str, Any]]:
    if not product_ids:
        return {}
    rows = run_db(
        "products_by_ids",
        "select id, name, category, price_cents, popularity from products where id = any(%s)",
        (product_ids,),
        fetch="all",
    )
    return {row[0]: product_to_dict(row) for row in rows}


def fetch_product(product_id: str, phase) -> dict[str, Any] | None:
    cache_key = f"product:{product_id}"
    cached = get_redis_client().get(cache_key)
    if cached:
        CACHE_REQUESTS.labels(service=SERVICE_NAME, cache="product", outcome="hit").inc()
        return json.loads(cached)
    CACHE_REQUESTS.labels(service=SERVICE_NAME, cache="product", outcome="miss").inc()
    rows = run_db(
        "product_detail",
        "select id, name, category, price_cents, popularity from products where id = %s",
        (product_id,),
        fetch="all",
    )
    if not rows:
        return None
    product = product_to_dict(rows[0])
    get_redis_client().setex(cache_key, phase.cache_ttl_seconds, json.dumps(product))
    return product


def search_products(term: str, phase) -> list[dict[str, Any]]:
    normalized = term.strip().lower() or "socks"
    cache_key = f"search:{normalized}"
    cached = get_redis_client().get(cache_key)
    if cached:
        CACHE_REQUESTS.labels(service=SERVICE_NAME, cache="search", outcome="hit").inc()
        return json.loads(cached)
    CACHE_REQUESTS.labels(service=SERVICE_NAME, cache="search", outcome="miss").inc()
    rows = run_db(
        "search_products",
        (
            "select id, name, category, price_cents, popularity "
            "from products "
            "where lower(name) like %s or lower(category) like %s "
            "order by popularity desc "
            "limit 8"
        ),
        (f"%{normalized}%", f"%{normalized}%"),
        fetch="all",
    )
    products = [product_to_dict(row) for row in rows]
    get_redis_client().setex(cache_key, phase.cache_ttl_seconds, json.dumps(products))
    return products


def get_cart(session_id: str) -> dict[str, Any]:
    raw_items = get_redis_client().hgetall(cart_key(session_id))
    items = {product_id: int(quantity) for product_id, quantity in raw_items.items()}
    products = fetch_products_by_ids(list(items))
    response_items = []
    total_rub = 0.0
    for product_id, quantity in items.items():
        product = products.get(product_id)
        if product is None:
            continue
        item_total = round(product["price_rub"] * quantity, 2)
        total_rub += item_total
        response_items.append(
            {
                "product_id": product_id,
                "name": product["name"],
                "quantity": quantity,
                "price_rub": product["price_rub"],
                "line_total_rub": item_total,
            }
        )
    return {
        "items": response_items,
        "item_count": sum(item["quantity"] for item in response_items),
        "total_rub": round(total_rub, 2),
    }


def count_all_cart_items() -> int:
    total = 0
    for key in get_redis_client().scan_iter(match="cart:*"):
        quantities = get_redis_client().hvals(key)
        total += sum(int(value) for value in quantities)
    return total


def count_pending_orders() -> int:
    row = run_db(
        "pending_orders",
        "select count(*) from orders where status in ('pending', 'processing')",
        fetch="one",
    )
    return int(row[0]) if row else 0


def update_phase_metrics(phase) -> None:
    for candidate in PHASES:
        active = 1.0 if candidate.name == phase.name else 0.0
        SCENARIO_PHASE.labels(service=SERVICE_NAME, phase=candidate.name).set(active)
        LATENCY_INJECTION.labels(service=SERVICE_NAME, phase=candidate.name).set(
            candidate.checkout_delay[1] if active else 0.0
        )
        ERROR_INJECTION.labels(service=SERVICE_NAME, phase=candidate.name).set(
            candidate.checkout_error_rate if active else 0.0
        )


def cleanup_sessions() -> int:
    cutoff = time.time() - SESSION_TTL_SECONDS
    with SESSIONS_LOCK:
        expired = [session_id for session_id, last_seen in SESSIONS.items() if last_seen < cutoff]
        for session_id in expired:
            SESSIONS.pop(session_id, None)
        return len(SESSIONS)


def app_housekeeping_loop() -> None:
    while True:
        try:
            phase = current_phase()
            update_phase_metrics(phase)
            ACTIVE_SESSIONS.labels(service=SERVICE_NAME).set(cleanup_sessions())
            QUEUE_DEPTH.labels(service=SERVICE_NAME).set(get_redis_client().llen("checkout-jobs"))
            ORDERS_PENDING.labels(service=SERVICE_NAME).set(count_pending_orders())
            TOTAL_CART_ITEMS.labels(service=SERVICE_NAME).set(count_all_cart_items())
        except Exception as error:            LOGGER.warning("Housekeeping iteration failed: %s", error)
        time.sleep(5)


def worker_housekeeping_loop() -> None:
    while True:
        try:
            phase = current_phase()
            update_phase_metrics(phase)
            queue_depth = get_redis_client().llen("checkout-jobs")
            QUEUE_DEPTH.labels(service=SERVICE_NAME).set(queue_depth)
            ORDERS_PENDING.labels(service=SERVICE_NAME).set(count_pending_orders())
            WORKER_BACKPRESSURE.labels(service=SERVICE_NAME).set(
                round(queue_depth / max(1, phase.target_users), 4)
            )
        except Exception as error:            LOGGER.warning("Worker housekeeping iteration failed: %s", error)
        time.sleep(5)


def start_daemon(target) -> None:
    thread = threading.Thread(target=target, daemon=True)
    thread.start()


@app.on_event("startup")
def on_startup() -> None:
    wait_for_dependencies()
    start_daemon(app_housekeeping_loop)


@app.get("/")
def root() -> dict[str, Any]:
    phase = current_phase()
    return {
        "service": SERVICE_NAME,
        "phase": phase.name,
        "docs": {
            "health": "/health",
            "metrics": "/metrics",
            "home": "/api/home",
            "catalog": "/api/catalog",
            "search": "/api/search?q=socks",
        },
    }


@app.get("/health")
def health() -> dict[str, Any]:
    phase = current_phase()
    return {
        "service": SERVICE_NAME,
        "phase": phase.name,
        "queue_depth": int(get_redis_client().llen("checkout-jobs")),
        "pending_orders": count_pending_orders(),
    }


@app.get("/metrics")
def metrics() -> Response:
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)


@app.get("/api/home")
def api_home(request: Request):
    def handler():
        phase = current_phase()
        session_id = current_session_id(request)
        burn_cpu(phase.request_cpu_burn_ms)
        random_sleep(phase.browse_delay)
        BUSINESS_EVENTS.labels(service=SERVICE_NAME, event="home_view", outcome="success").inc()
        return {"session_id": session_id, "phase": phase.name, "products": fetch_featured_products()}

    return execute_endpoint("/api/home", "GET", handler, "home_failed")


@app.get("/api/catalog")
def api_catalog(request: Request):
    def handler():
        phase = current_phase()
        session_id = current_session_id(request)
        burn_cpu(phase.request_cpu_burn_ms)
        random_sleep(phase.product_delay)
        BUSINESS_EVENTS.labels(service=SERVICE_NAME, event="catalog_view", outcome="success").inc()
        return {"session_id": session_id, "phase": phase.name, "products": fetch_featured_products(limit=12)}

    return execute_endpoint("/api/catalog", "GET", handler, "catalog_failed")


@app.get("/api/search")
def api_search(request: Request, q: str = "socks"):
    def handler():
        phase = current_phase()
        session_id = current_session_id(request)
        burn_cpu(phase.request_cpu_burn_ms)
        random_sleep(phase.search_delay)
        products = search_products(q, phase)
        BUSINESS_EVENTS.labels(service=SERVICE_NAME, event="search", outcome="success").inc()
        return {"session_id": session_id, "phase": phase.name, "query": q, "results": products}

    return execute_endpoint("/api/search", "GET", handler, "search_failed")


@app.get("/api/product/{product_id}")
def api_product(request: Request, product_id: str):
    def handler():
        phase = current_phase()
        session_id = current_session_id(request)
        burn_cpu(phase.request_cpu_burn_ms)
        random_sleep(phase.product_delay)
        product = fetch_product(product_id, phase)
        if product is None:
            raise HTTPException(status_code=404, detail="product_not_found")
        BUSINESS_EVENTS.labels(service=SERVICE_NAME, event="product_view", outcome="success").inc()
        return {"session_id": session_id, "phase": phase.name, "product": product}

    return execute_endpoint("/api/product", "GET", handler, "product_failed")


@app.post("/api/cart/add")
def api_cart_add(request: Request, payload: CartAddRequest):
    def handler():
        phase = current_phase()
        session_id = current_session_id(request)
        product = fetch_product(payload.product_id, phase)
        if product is None:
            raise HTTPException(status_code=404, detail="product_not_found")
        burn_cpu(phase.request_cpu_burn_ms)
        random_sleep(phase.cart_delay)
        cart = get_redis_client()
        cart.hincrby(cart_key(session_id), payload.product_id, payload.quantity)
        cart.expire(cart_key(session_id), SESSION_TTL_SECONDS)
        BUSINESS_EVENTS.labels(service=SERVICE_NAME, event="cart_add", outcome="success").inc()
        return {"session_id": session_id, "phase": phase.name, "cart": get_cart(session_id)}

    return execute_endpoint("/api/cart/add", "POST", handler, "cart_add_failed")


@app.get("/api/cart")
def api_cart(request: Request):
    def handler():
        phase = current_phase()
        session_id = current_session_id(request)
        random_sleep(phase.cart_delay)
        BUSINESS_EVENTS.labels(service=SERVICE_NAME, event="cart_view", outcome="success").inc()
        return {"session_id": session_id, "phase": phase.name, "cart": get_cart(session_id)}

    return execute_endpoint("/api/cart", "GET", handler, "cart_failed")


@app.post("/api/checkout")
def api_checkout(request: Request):
    def handler():
        phase = current_phase()
        session_id = current_session_id(request)
        cart = get_cart(session_id)
        if cart["item_count"] == 0:
            raise HTTPException(status_code=409, detail="empty_cart")
        burn_cpu(max(phase.request_cpu_burn_ms, 1) * 2)
        random_sleep(phase.checkout_delay)
        if RANDOM.random() < phase.checkout_error_rate:
            BUSINESS_EVENTS.labels(service=SERVICE_NAME, event="checkout", outcome="error").inc()
            raise HTTPException(status_code=503, detail="checkout_degraded")
        order = run_db(
            "insert_order",
            (
                "insert into orders (session_id, status, item_count, total_cents, phase_name) "
                "values (%s, 'pending', %s, %s, %s) returning id"
            ),
            (
                session_id,
                cart["item_count"],
                int(round(cart["total_rub"] * 100)),
                phase.name,
            ),
            fetch="one",
        )
        order_id = int(order[0])
        get_redis_client().lpush(
            "checkout-jobs",
            json.dumps(
                {
                    "order_id": order_id,
                    "session_id": session_id,
                    "total_rub": cart["total_rub"],
                    "phase": phase.name,
                }
            ),
        )
        get_redis_client().delete(cart_key(session_id))
        CHECKOUT_VALUE.labels(service=SERVICE_NAME).observe(cart["total_rub"])
        BUSINESS_EVENTS.labels(service=SERVICE_NAME, event="checkout", outcome="success").inc()
        return {
            "session_id": session_id,
            "phase": phase.name,
            "order_id": order_id,
            "status": "pending",
            "total_rub": cart["total_rub"],
        }

    return execute_endpoint("/api/checkout", "POST", handler, "checkout_failed")


def worker_loop() -> None:
    wait_for_dependencies()
    start_http_server(METRICS_PORT)
    start_daemon(worker_housekeeping_loop)
    LOGGER.info("Worker metrics exposed on port %s", METRICS_PORT)
    while True:
        phase = current_phase()
        queue_item = get_redis_client().brpop("checkout-jobs", timeout=3)
        if queue_item is None:
            continue
        started_at = time.perf_counter()
        outcome = "success"
        try:
            payload = json.loads(queue_item[1])
            burn_cpu(max(phase.worker_cpu_burn_ms, 1) * 2)
            random_sleep(phase.worker_delay)
            status = "shipped"
            if RANDOM.random() < phase.worker_error_rate:
                status = "failed"
                outcome = "error"
            run_db(
                "update_order_status",
                "update orders set status = %s, processed_at = now() where id = %s",
                (status, payload["order_id"]),
            )
            BUSINESS_EVENTS.labels(service=SERVICE_NAME, event="fulfillment", outcome=outcome).inc()
        except Exception as error:            outcome = "error"
            LOGGER.warning("Worker job failed: %s", error)
        finally:
            WORKER_JOBS.labels(service=SERVICE_NAME, job_type="checkout", outcome=outcome).inc()
            WORKER_DURATION.labels(service=SERVICE_NAME, job_type="checkout", outcome=outcome).observe(
                time.perf_counter() - started_at
            )


def main() -> None:
    role = sys.argv[1] if len(sys.argv) > 1 else os.getenv("ROLE", "api")
    if role == "worker":
        worker_loop()
        return
    uvicorn.run(app, host="0.0.0.0", port=APP_PORT, log_level="info")


if __name__ == "__main__":
    main()
